import type { Station } from "./types";

export const demoStations: Station[] = [
  {
    id: "1",
    name: "Tel Aviv Central Station Hub",
    address: "Arlozorov 106",
    city: "Tel Aviv",
    country: "Israel",
    power: "DC 150kW",
    network: "EVgo",
    lat: 32.0853,
    lng: 34.7818,
  },
  {
    id: "2",
    name: "Jerusalem Mall Chargers",
    address: "Agudat Sport Beitar 1",
    city: "Jerusalem",
    country: "Israel",
    power: "AC 22kW",
    network: "ChargePoint",
    lat: 31.7683,
    lng: 35.2137,
  },
  {
    id: "3",
    name: "Haifa Port Fast Charge",
    address: "HaNamal 1",
    city: "Haifa",
    country: "Israel",
    power: "DC 100kW",
    network: "Tesla",
    lat: 32.8184,
    lng: 34.9885,
  },
  {
    id: "4",
    name: "Beer Sheva University",
    address: "Ben-Gurion University Campus",
    city: "Beer Sheva",
    country: "Israel",
    power: "AC 11kW",
    network: "EVgo",
    lat: 31.2618,
    lng: 34.7995,
  },
  {
    id: "5",
    name: "Eilat Marina Supercharger",
    address: "HaMarina 1",
    city: "Eilat",
    country: "Israel",
    power: "DC 250kW",
    network: "Tesla",
    lat: 29.5581,
    lng: 34.9482,
  },
  {
    id: "6",
    name: "Netanya Promenade Charge",
    address: "HaTayelet 12",
    city: "Netanya",
    country: "Israel",
    power: "DC 50kW",
    network: "EVgo",
    lat: 32.3328,
    lng: 34.8601,
  },
  {
    id: "7",
    name: "Herzliya Business Park",
    address: "Maskit 27",
    city: "Herzliya",
    country: "Israel",
    power: "AC 22kW",
    network: "ChargePoint",
    lat: 32.1614,
    lng: 34.8098,
  },
  {
    id: "8",
    name: "Petah Tikva Shopping Center",
    address: "Hamabria 2",
    city: "Petah Tikva",
    country: "Israel",
    power: "DC 75kW",
    network: "Electreon",
    lat: 32.0878,
    lng: 34.8878,
  },
  {
    id: "9",
    name: "Ramat Gan Diamond Exchange",
    address: "Jabotinsky 2",
    city: "Ramat Gan",
    country: "Israel",
    power: "DC 100kW",
    network: "EVgo",
    lat: 32.0776,
    lng: 34.8083,
  },
  {
    id: "10",
    name: "Rishon LeZion City Hall",
    address: "Rothschild 50",
    city: "Rishon LeZion",
    country: "Israel",
    power: "AC 22kW",
    network: "ChargePoint",
    lat: 31.9642,
    lng: 34.8019,
  },
  {
    id: "11",
    name: "Ashdod Port Supercharger",
    address: "HaNamal 5",
    city: "Ashdod",
    country: "Israel",
    power: "DC 150kW",
    network: "Tesla",
    lat: 31.8040,
    lng: 34.6551,
  },
  {
    id: "12",
    name: "Rehovot Weizmann Institute",
    address: "Herzl 234",
    city: "Rehovot",
    country: "Israel",
    power: "AC 11kW",
    network: "EVgo",
    lat: 31.8981,
    lng: 34.8109,
  },
  {
    id: "13",
    name: "Holon Industrial Zone",
    address: "Golda Meir 5",
    city: "Holon",
    country: "Israel",
    power: "DC 50kW",
    network: "Electreon",
    lat: 32.0158,
    lng: 34.7791,
  },
  {
    id: "14",
    name: "Bat Yam Beach Front",
    address: "Ben Gurion 100",
    city: "Bat Yam",
    country: "Israel",
    power: "AC 22kW",
    network: "ChargePoint",
    lat: 32.0231,
    lng: 34.7505,
  },
  {
    id: "15",
    name: "Nahariya Northern Gate",
    address: "Gaaton 1",
    city: "Nahariya",
    country: "Israel",
    power: "DC 75kW",
    network: "EVgo",
    lat: 33.0074,
    lng: 35.0972,
  },
  {
    id: "16",
    name: "Tiberias Kinneret Shore",
    address: "HaGalil 1",
    city: "Tiberias",
    country: "Israel",
    power: "DC 100kW",
    network: "Tesla",
    lat: 32.7940,
    lng: 35.5300,
  },
  {
    id: "17",
    name: "Modi'in Tech Park",
    address: "Yitzhak Rabin 9",
    city: "Modi'in",
    country: "Israel",
    power: "AC 22kW",
    network: "ChargePoint",
    lat: 31.8960,
    lng: 35.0100,
  },
  {
    id: "18",
    name: "Ashkelon Marina Charger",
    address: "HaMarina 3",
    city: "Ashkelon",
    country: "Israel",
    power: "DC 50kW",
    network: "EVgo",
    lat: 31.6658,
    lng: 34.5664,
  },
  {
    id: "19",
    name: "Kfar Saba Town Square",
    address: "Weizmann 1",
    city: "Kfar Saba",
    country: "Israel",
    power: "AC 11kW",
    network: "Electreon",
    lat: 32.1751,
    lng: 34.9071,
  },
  {
    id: "20",
    name: "Ra'anana Central Park",
    address: "Ahuza 100",
    city: "Ra'anana",
    country: "Israel",
    power: "DC 75kW",
    network: "EVgo",
    lat: 32.1848,
    lng: 34.8713,
  },
  {
    id: "21",
    name: "Givat Shmuel Fast Charge",
    address: "Bar Ilan University",
    city: "Givat Shmuel",
    country: "Israel",
    power: "DC 150kW",
    network: "ChargePoint",
    lat: 32.0643,
    lng: 34.8426,
  },
  {
    id: "22",
    name: "Yehud Industrial Zone",
    address: "HaMelaha 10",
    city: "Yehud",
    country: "Israel",
    power: "AC 22kW",
    network: "Electreon",
    lat: 32.0324,
    lng: 34.8919,
  },
  {
    id: "23",
    name: "Lod Airport Road",
    address: "Ben Gurion Airport Access",
    city: "Lod",
    country: "Israel",
    power: "DC 250kW",
    network: "Tesla",
    lat: 31.9983,
    lng: 34.8988,
  },
  {
    id: "24",
    name: "Ramla City Center",
    address: "HaHerut 15",
    city: "Ramla",
    country: "Israel",
    power: "AC 11kW",
    network: "EVgo",
    lat: 31.9284,
    lng: 34.8714,
  },
  {
    id: "25",
    name: "Bnei Brak Highway Stop",
    address: "Jabotinsky 80",
    city: "Bnei Brak",
    country: "Israel",
    power: "DC 100kW",
    network: "ChargePoint",
    lat: 32.0833,
    lng: 34.8319,
  },
  {
    id: "26",
    name: "Kiryat Ono East Mall",
    address: "Abba Hillel 10",
    city: "Kiryat Ono",
    country: "Israel",
    power: "AC 22kW",
    network: "Electreon",
    lat: 32.0613,
    lng: 34.8563,
  },
  {
    id: "27",
    name: "Or Yehuda Tech Campus",
    address: "Kremenetski 36",
    city: "Or Yehuda",
    country: "Israel",
    power: "DC 50kW",
    network: "EVgo",
    lat: 32.0337,
    lng: 34.8573,
  },
  {
    id: "28",
    name: "Nazareth Old City Charger",
    address: "Paul VI St 1",
    city: "Nazareth",
    country: "Israel",
    power: "AC 22kW",
    network: "ChargePoint",
    lat: 32.6996,
    lng: 35.2952,
  },
  {
    id: "29",
    name: "Acre Historic Port",
    address: "Old City Harbor",
    city: "Acre",
    country: "Israel",
    power: "DC 75kW",
    network: "Tesla",
    lat: 32.9243,
    lng: 35.0680,
  },
  {
    id: "30",
    name: "Safed Artists Quarter",
    address: "HaMeiri 3",
    city: "Safed",
    country: "Israel",
    power: "AC 11kW",
    network: "EVgo",
    lat: 32.9646,
    lng: 35.4961,
  },
];
